# SPDX-FileCopyrightText: 2026 Martijn van der Ven
# SPDX-License-Identifier: 0BSD

version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
      semver-major-days: 14
    commit-message:
      prefix: "build"
      include: scope
  - package-ecosystem: gomod
    directory: "/tools"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
      semver-major-days: 14
    commit-message:
      prefix: "ci"
      include: scope
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
      semver-major-days: 14
    commit-message:
      prefix: "ci"
      include: scope
